{% set name = "dask-jobqueue" %}
{% set version = "0.8.3" %}
{% set sha256 = "92ed43b604ef74fd6b9b54655e67ad1f2275c1889bb60bc9ebd26bb4a5e6a2d8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dask-core >=2022.02.0
    - distributed >=2022.02.0

test:
  imports:
    - dask_jobqueue

about:
  home: https://github.com/dask/dask-jobqueue
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Easy deployment of Dask Distributed on job queuing systems like PBS, Slurm, LSF and SGE.
  description: |
    Easy deployment of Dask Distributed on job queuing systems such as PBS,
    Slurm, LSF or SGE.
  doc_url: https://jobqueue.dask.org
  dev_url: https://github.com/dask/dask-jobqueue

extra:
  recipe-maintainers:
    - jhamman
    - mrocklin
    - lesteve
    - guillaumeeb
    - andersy005
